version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
  exclusions:
    paths:
      - graph/generated.go
      - graph/models_gen.go
      - graph/schema.resolvers.go

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jsr-probitas
